import { Header } from "app/components/shared/Header/Header";
import { Footer } from "app/components/shared/Footer";
import 'app/sass/global.sass'
import {Roboto} from 'next/font/google'

const roboto= Roboto({
  weight: ['100', '300' , '400' , '500' , '700'],
  subsets: ['latin']}
)
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Items store",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
